### PR TITLE
Add a command line script to import one or more GPX files

### LINKED ISSUE #53: Mass Import via CommandLine
It would be nice to be able to mass import by running a script pointed at a specific directory full of gpx files.

### PR DESCRIPTION
**Pull request by markus-schuster**
I had the need to import GPX files from command line, so I created a small PHP script by combining parts of the existing `utils/import.php` with `ulrichsg/getopt-php` for argument parsing and a bit of glue code to hold it all together.
Sorry for the external dependency, but command line argument parsing seems to be really PITA in PHP :disappointed: I was a bit unsure how you would like to manage such external dependencies, so for now I simply commited the `vendor` folder.

I guess this would also fix #53 

When it comes to features I'll let the script speak for itself.
```
$ utils/import_cli.php --help
Usage: utils/import_cli.php [options] <gpx> [<gpx>...]

Operands:
  <gpx>  One or more GPX files to import

Options:
  -h, --help                   Show usage/help
  -u, --user-id [<arg>]        Which user to import the track(s) for (default:
                               1)
  -e, --import-existing-track  Import already existing tracks (based on track
                               name)
  -l, --skip-last-track        Skip the last track (for special use cases)
```

### CODE REVIEW

**Comment by markus-schuster** [comment]
Hey Bartek,
at first I started with the built-in getopt function (tried to avoid external dependencies as well) but ran into problems rather quickly. It started with minor inconveniences like there can't be a space between a short option and its value (at least in my PHP installation), which could confuse users as it's a rather standard feature (and the code would have to handle this case on its own). Then there's the problem with positional parameters (the GPX files in this case) - the built-in getopt function has no support for those at all. The `optind` parameter introduced in PHP 7.1 could come handy for that, but I'm unsure if it's safe to assume every user is on PHP 7.1+ (I'm on Debian stable, which ships 7.0 right now). Also there's no built-in error handling at all, users can just pass arbitrary parameters and getopt will not care about unknown parameters, a case the code would have to handle as well.
Maybe it's because I'm coming from a Python background (and my PHP days are more than 10 years ago :smile:), but at this point I stopped and looked out for some good external library to not reinvent the wheel.

**Comment by bfabiszewski** [comment]
Could you please remove `vendor` folder from PR? I will add dependecies through composer.

**Comment by markus-schuster** [comment]
Hi Bartek,
sorry for the delay, I quickly reverted my commit adding the vendor folder, hope that does the job.
Markus

**Comment by bfabiszewski** [comment]
Thanks a lot!

**Pull request merged**
