### PR TITLE
Fix and update translation

### PR DESCRIPTION
**Pull request by MAH69IK**
I not translate "Stroke weight" and "Stroke opacity" becouse I don't understand what does this mean on the map.
I alsa not find in UI "Add", "Edit", "Delete" so don't change this. And don't know what is extra marker and hilite marker.

### CODE REVIEW

**Comment by bfabiszewski** [comment]
Great, thanks!

Stroke weight is width of the track line on the map. The width of the red line on the image below.
image

Stroke opacity is transparency level of the same track line. Zero means transparent and one opaque color. 
BTW, terms come from google maps api: `strokeColor`, `strokeWeight`, `strokeOpacity`.

Add, Edit and Delete are captions for the icons below (in image `alt` attribute). These are not visible directly but available for screen readers etc.
image

Extra marker is a special marker that shows that the point has attached image or comment. This is the marker on the left side of the image below.
image

Hilite marker. When you click a point on the altitudes chart the respective marker is highlighted on the map.
image

**Comment by bfabiszewski** [comment]
Could you update the translation with missing strings? According to above guidelines.

**Comment by MAH69IK** [comment]
@bfabiszewski yes! Thanks for the tips :) I was away, so I couldn't do it earlier.

**Comment by MAH69IK** [comment]
Done.

**Comment by bfabiszewski** [comment]
Great, thanks a lot!

**Pull request merged**
