### PR TITLE
Catalan Translation

### PR DESCRIPTION
**Pull request by francrodriguez**
New translation to catalan.

### CODE REVIEW

**Comment by bfabiszewski** [comment]
Thanks again!

**Comment by bfabiszewski** [comment]
I noticed that some strings are still missing for both Catalan and Spanish. You may have a look and add them at [Transifex](https://www.transifex.com/bfabiszewski/ulogger/dashboard/).

I also noticed that Spanish translation uses two words for track. In some cases it is translated as "track" while in others as "ruta". This is probably the result of merging different translations by different people. Don't you think it should be unified? Which word better fits to our context?

**Comment by francrodriguez** [comment]
Ok! I'll go to transifex in order to complete the translations.

In other applications, "track" is translated to "ruta", and also the "academic" way use "ruta" as translation.
IMHO we should use "ruta".

And many thanks for your great application!

**Comment by bfabiszewski** [comment]
Great, I added you as translator to transifex team.

**Pull request merged**
