### PR TITLE
Toggle Waypoints / Hack to ignore 0 altitude

### PR DESCRIPTION
**Pull request by Lebewesen**
Hiding and displaying Waypoints

The 0 altitude is a hack at the moment - 0 altitude could be possible, but i think 0 without a position after decimal point is unlikly.

I make a better fix when I have time... maybe in one or two weeks. You could decide if you would like to merge the hack.

### CODE REVIEW

**Comment by Lebewesen** [comment]
I rewrite the toggle without jquery

**Comment by bfabiszewski** [comment]
Thanks for another contribution!

You are right, that it is an overkill to include jquery just for that feature.

Regarding zero altitudes I am not sure about this hack. Unfortunately Android devices supply incorrect data. I will think about it.

Please also note that in recent commits I moved check for null altitude to [another function](https://github.com/bfabiszewski/ulogger-server/blob/67f407635bdff624cb48cf76c95f46242206e4f8/js/main.js#L153), to filter out null at the point when altitudes array is created.

**Comment by Lebewesen** [comment]
I wrote this fix for me in the middle of the night on vacation when I couldn't sleep  ;-)
I think both fixes are hacks - so I closed the pull request - I think I make it better.
I have an idea for a solution(workaround) of the 0 problem and the toggle. I think I do it the next two to three weeks.

I also have a crappy hack for the speed histogram I did this night. But I don't know how to do it better. If you like I can give you the code for the speed histogram.

**Comment by bfabiszewski** [comment]
Thanks! Take your time. 
A good working solution is always preferable over "crappy hack" :)

**Pull request closed without merging**
